### ISSUE TITLE
webpack errors, unable to find ReactDrag component

### ISSUE THREAD

**Issue by sriprabha** [mgechev/react-reorderable#10]
I am seeing the following error where it is not able to find react drag component. 
`ERROR in ./~/react-reorderable/dist/react-reorderable.js
Module not found: Error: Cannot resolve module 'ReactDrag' in /Users/xxx/Projects/theme-pages-tool/node_modules/react-reorderable/dist
 @ ./~/react-reorderable/dist/react-reorderable.js 3:4-43`

I am importing React, and react-reporderable component in my file, and then creating a ReactElement as given in the demo: https://github.com/mgechev/react-reorderable/blob/master/demo/index.html#L65 . Am I missing something here?

**Comment by mgechev** [comment]
Would you provide me a step-by-step scenario how to reproduce it?

[Here's the place](https://github.com/mgechev/react-reorderable/blob/master/dist/react-reorderable.js#L5) where `react-drag` is referenced.

After running `npm install react-reorderable`, `react-drag` should be inside: `node_modules/react-reorderable/node_modules/react-drag`.
