### ISSUE TITLE
Warnings under React 0.14

### ISSUE THREAD

**Issue by nzbart** [mgechev/react-reorderable#14]
Now that React 0.14 has been released, would it be possible to make some changes to avoid deprecation warnings when running under the new version?

When using this component under [0.14.1](https://facebook.github.io/react/blog/2015/10/28/react-v0.14.1.html), we see:

```
> Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.
> Warning: cloneWithProps(...) is deprecated. Please use React.cloneElement instead.
```

My understanding is that these deprecated functions will be removed in the next version of React.

Info on the 0.14 release can be found [here](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html).

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/react-reorderable/commit/4918961aab832a8fa6b5de6dd981a8117bb43bca
