### ISSUE TITLE
Warning: Component's children should not be mutated.

### ISSUE THREAD

**Issue by peebles** [mgechev/react-reorderable#18]
I am getting this warning **a lot**.  I think I've traced it down to these lines of code.  The setState() seems to be causing the warning message, and its happening on every mouse up.

``` javascript
var ReactReorderable = React.createClass({
  componentWillMount: function () {
    window.addEventListener('mouseup', this._mouseupHandler = function () {
      this.setState({
        mouseDownPosition: null
      });
    }.bind(this));
  },
```

**Comment by mgechev** [comment]
Hey @peebles, here's more information https://github.com/mgechev/react-reorderable/issues/17#issuecomment-244695730. Most likely I'll not keep updating the library because I'm involved in other projects. I'll add a deprecation notice.

**Comment by peebles** [comment]
What do you mean "deprecation notice"?  You mean, the entire 
react-reorderable component is deprecated?  I am using react 15.3.2 so, 
I don't _think_ I am doing anything that's deprecated...

If you are deprecating the entire component, then :( I like it.  Any 
recommendations for a replacement?  I am using react-grid-layout and I 
think that might be configured into a suitable behavioral replacement, 
but yours has a simpler api for a simple list.

**Comment by mgechev** [comment]
Yes, I mean deprecating `react-reorderable`. In order to keep it up to date with the latest react changes I'll need to rewrite most of it.
