### ISSUE TITLE
cannot find module React

### ISSUE THREAD

**Issue by prakharsingh** [mgechev/react-reorderable#4]
Hi, I just install your npm package and I  am getting an error which says:
Cannot find module 'React'
at /node_modules/react-reorderable/dist/react-reorderable.js:5:30
at /node_modules/react-reorderable/dist/react-reorderable.js:9:2

I am using react js v0.13.3 and node v0.12.2.

**Comment by mgechev** [comment]
Are you using any module system (commonjs, es2015 modules, amd) or loading react with script tag?

In all cases you most likely haven't included reference to react.js.
