### ISSUE TITLE
Problems launching from NPM

### ISSUE THREAD

**Issue by nzbart** [mgechev/react-reorderable#5]
When I knock up a demo in [CodePen](http://codepen.io/anon/pen/eNqeyN), the component works well. However, when I pull in react-reorderable via npm and reference it using Browserify, it fails at runtime with the following error:

```
Uncaught TypeError: Cannot read property '_currentElement' of null
```

I suspect this problem may be caused by a dependency not being loaded. Do you have any ideas on what I'm doing wrong?

Below is a simple app that demonstrates the problem I'm having:

_package.json_

``` javascript
{
  "name": "demo",
  "scripts": {
    "build": "browserify -d -t babelify App.jsx > app.js"
  },
  "dependencies": {
    "react": "^0.13.3",
    "react-reorderable": "^0.1.4"
  },
  "devDependencies": {
    "babelify": "^6.2.0",
    "browserify": "^11.0.1"
  }
}
```

_index.html_

``` javascript
<html>
    <head>
        <script src="app.js" defer></script>
    </head>
    <body id=ReactApp></body>
</html>
```

_App.jsx_

``` javascript
import React from 'react/addons';
import ReactReorderable from 'react-reorderable';

React.render(
    <ReactReorderable>
        <div>1</div>
        <div>2</div>
        <div>3</div>
        <div>4</div>
        <div>5</div>
    </ReactReorderable>,
    document.getElementById('ReactApp')
);
```

**Steps to reproduce:**
1. Save the three files into a directory.
2. Run `npm install`
3. Run `npm run build`
4. Load _index.html_ in your browser

**Comment by mgechev** [comment]
Thanks for pointing this out! I'll add it to my todo list and try to come back to you as soon as possible.

**Comment by cjmoran** [comment]
Same thing happens when using Webpack.

Webpack has also started throwing about a bajillion WARNINGs when packaging since I added react-reorderable to my project. Maybe these issues are related? (Even if not, would appreciate a solution to both of these regardless). The warnings look like this:

```
WARNING in ../~/react/lib/React.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ../~/React/lib/React.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ../~/react/lib/EventPluginUtils.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ../~/React/lib/EventPluginUtils.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

...
```

Each one is indeed repeated twice. Seems to be some issue related to using `require('React')` rather than `require('react')` as far as I can tell, but I haven't dug into it very deeply.

**Comment by mgechev** [comment]
https://github.com/mgechev/react-reorderable/commit/4fe1844292de9f0096ee0d5383cd46a2f55dbada should fix the problem. Let me know if there're any other errors.

@culmor30 I think you should no longer get the warnings you posted.

**Comment by sriprabha** [comment]
@mgechev I see the same warnings as above. I installed the component from npm , npm -i react-reorderable.

**Comment by nzbart** [comment]
@mgechev Your fix resolved the issue for us. Thanks!
