### ISSUE TITLE
[Bug] Issue when dragging element below viewport

### ISSUE THREAD

**Issue by Neaox** [mgechev/react-reorderable#7]
If you have a list of sortable elements which is longer than the viewport (i.e the viewport has a scrollbar) and you drag the element below the viewport, causing the viewport to scroll down, the element being dragged is no longer below the cursor. (See attached gif).
![react-reorderable-bug](https://cloud.githubusercontent.com/assets/13699847/9723082/3c73f726-560e-11e5-951a-2ba53db400dd.gif)

**Comment by mgechev** [comment]
Thanks for the issue! This might be an issue in [react-drag](https://github.com/mgechev/react-drag) as well, I'll take a look at it as soon as possible.

**Comment by mgechev** [comment]
@Neaox should work with react-drag v0.1.5.
