### ISSUE TITLE
Remove/replace classSet addon

### ISSUE THREAD

**Issue by Neaox** [mgechev/react-reorderable#8]
Component needs to be updated to remove/replace the classSet react addon as it will be deprecated in a future version.

> Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset

**Comment by mgechev** [comment]
This warning is caused by [react-drag](https://github.com/mgechev/react-drag).
https://github.com/mgechev/react-drag/issues/2
